version: '3'
networks:
  otus-randomization-network:
services:
  otus-randomization-database:
    build:
      context: mongodb
      dockerfile: Dockerfile
    container_name: otus-randomization-database
    restart: always
    volumes:
      - ./mongodb/persistence/mongoData/:/data/db/
    ports:
      - 27017:27017
    networks:
      - otus-randomization-network
  otus-randomization:
    build:
      context: nodejs/api
      dockerfile: Dockerfile
    container_name: otus-randomization
    restart: always
    depends_on:
      - otus-randomization-database
    links:
      - otus-randomization-database
    ports:
      - 80:3005
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - otus-randomization-network



