version: '3'
networks:
  otus-randomization-network:
services:
  db:
    image: mongo:4.0
    container_name: db
    restart: always
    volumes:
      - ./mongodb/persistence/mongoData/:/data/db/
      - ./mongodb/config/mongo.conf:/etc/mongo.conf
      - ./mongodb/config/initdb.js:/docker-entrypoint-initdb.d/initdb.js
    ports:
      - 27017:27017
    command:
      - '--auth'
      - '-f'
      - '/etc/mongo.conf'
    networks:
      - otus-randomization-network
  otus-randomization:
    build:
      context: nodejs/api
      dockerfile: Dockerfile
    container_name: otus-randomization
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 80:3001
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    networks:
      - otus-randomization-network



