FROM bitnami/mongodb:4.0
LABEL mantainer otussolutions/mongodb-secondary
ENV MONGODB_REPLICA_SET_MODE secondary
ENV MONGODB_PRIMARY_HOST otus-randomization-db
ENV MONGODB_PRIMARY_ROOT_PASSWORD XRYs9yjU
ENV MONGODB_REPLICA_SET_KEY replicasetkey123

EXPOSE 27017
